#!/usr/bin/env bash
set -e

# TODO: if macos/linux, do sth else
if [[ $(uname -s) == 'Darwin' ]]; then
    open -na "PyCharm.app" --args "$@"
    exit 0
fi


## WSL/Windows:

latest_version="$(ls -lQd /mnt/c/Program\ Files/JetBrains/PyCharm* | awk -F'"' '{print $2}' | grep -oP '[.0-9]+' | sort -rV | head -1)"
# e.g. '2021.1.1'

app_dir="$(ls -lQd /mnt/c/Program\ Files/JetBrains/PyCharm*${lv} | awk -F'"' '{print $2}' | head -1)"
# e.g. '/mnt/c/Program Files/JetBrains/PyCharm 2021.1.1'

"$app_dir"/bin/pycharm64.exe "${*}" > /dev/null 2>&1 &
